config/routes.rb
Rails.application.routes.draw do

  resources :workout_categories
  resources :user_workouts do
    collection do
      get 'search_workout' => 'user_workouts#search_workout'
    end
  end 
  
  resources :workouts 
  # get 'dashboards/index'
  get "/dashboards", to: "dashboards#index"

  resources :meals
  resources :posts
  resources :categories
  devise_for :users	
  resources :todos

  root to: "dashboards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
# == Schema Information
#
# Table name: workouts
#
#  id                  :integer          not null, primary key
#  name                :string
#  description         :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  workout_category_id :integer
#  pictograms          :json
#

class Workout < ApplicationRecord
  mount_uploaders :pictograms, AvatarUploader

  has_many :user_workouts
	has_many :users, through: :user_workouts

	belongs_to :workout_category

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:name, :description, :workout_category_id, {pictograms: []})
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.haml
= form_for(@workout, html: { class: "form-horizontal", role: "form" }, style: 'display:none') do |f|
  - if @workout.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@workout.errors.count, "error")
        prohibited this workout from being saved:
      %ul
        - @workout.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.collection_select(:workout_category_id, WorkoutCategory.all, :id, :name, prompt: true, class: "form-control")
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"
  .form-group
    = f.label :pictograms, class: "col-sm-2 control-label"
    .col-sm-10
      = f.file_field :pictograms, multiple: true
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/workouts/edit.html.haml
.page-header
  = link_to workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @workout, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing workout
= render 'form'

app/views/workouts/index.html.haml
.page-header
  = link_to new_workout_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Workout
  %h1 Listing workouts
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Pictogram
        %th Name
        %th Description
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @workouts) do |workout|
        %td.thumbnail{:style => "padding:0;background-color:#333;text-align:center;margin: 0"}
          = image_tag (workout.pictograms.first.url rescue 'no image'), style: 'padding: 3px', size: '90x90'
        %td= workout.name
        %td= workout.description
        %td= link_to 'Show', workout
        %td= link_to 'Edit', edit_workout_path(workout)
        %td= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' }

app/views/workouts/new.html.haml
.page-header
  = link_to workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New workout
= render 'form'

app/views/workouts/show.html.haml
.page-header
  = link_to workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_workout_path(@workout), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show workout
%dl.dl-horizontal
  %dt Name:
  %dd= @workout.name
  %dt Description:
  %dd= @workout.description