config/routes.rb
Rails.application.routes.draw do

  resources :workout_categories
  resources :user_workouts do
    collection do
      get 'search_workout' => 'user_workouts#search_workout'
    end
  end 
  
  resources :workouts 
  # get 'dashboards/index'
  get "/dashboards", to: "dashboards#index"

  resources :meals
  resources :posts
  resources :categories
  devise_for :users	
  resources :todos

  root to: "dashboards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout_category.rb
# == Schema Information
#
# Table name: workout_categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class WorkoutCategory < ApplicationRecord
end

app/controllers/workout_categories_controller.rb
class WorkoutCategoriesController < ApplicationController
  before_action :set_workout_category, only: [:show, :edit, :update, :destroy]

  # GET /workout_categories
  # GET /workout_categories.json
  def index
    @workout_categories = WorkoutCategory.all
  end

  # GET /workout_categories/1
  # GET /workout_categories/1.json
  def show
  end

  # GET /workout_categories/new
  def new
    @workout_category = WorkoutCategory.new
  end

  # GET /workout_categories/1/edit
  def edit
  end

  # POST /workout_categories
  # POST /workout_categories.json
  def create
    @workout_category = WorkoutCategory.new(workout_category_params)

    respond_to do |format|
      if @workout_category.save
        format.html { redirect_to @workout_category, notice: 'Workout category was successfully created.' }
        format.json { render :show, status: :created, location: @workout_category }
      else
        format.html { render :new }
        format.json { render json: @workout_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_categories/1
  # PATCH/PUT /workout_categories/1.json
  def update
    respond_to do |format|
      if @workout_category.update(workout_category_params)
        format.html { redirect_to @workout_category, notice: 'Workout category was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_category }
      else
        format.html { render :edit }
        format.json { render json: @workout_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_categories/1
  # DELETE /workout_categories/1.json
  def destroy
    @workout_category.destroy
    respond_to do |format|
      format.html { redirect_to workout_categories_url, notice: 'Workout category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_category
      @workout_category = WorkoutCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_category_params
      params.require(:workout_category).permit(:name, :description)
    end
end

app/helpers/workout_categories_helper.rb
module WorkoutCategoriesHelper
end

app/views/workout_categories/_form.html.haml
= form_for(@workout_category, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @workout_category.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@workout_category.errors.count, "error")
        prohibited this workout_category from being saved:
      %ul
        - @workout_category.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/workout_categories/edit.html.haml
.page-header
  = link_to workout_categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @workout_category, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing workout_category
= render 'form'

app/views/workout_categories/index.html.haml
.page-header
  = link_to new_workout_category_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Workout category
  %h1 Listing workout_categories
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Description
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @workout_categories) do |workout_category|
        %td= workout_category.name
        %td= workout_category.description
        %td= link_to 'Show', workout_category
        %td= link_to 'Edit', edit_workout_category_path(workout_category)
        %td= link_to 'Destroy', workout_category, method: :delete, data: { confirm: 'Are you sure?' }

app/views/workout_categories/new.html.haml
.page-header
  = link_to workout_categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New workout_category
= render 'form'

app/views/workout_categories/show.html.haml
.page-header
  = link_to workout_categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_workout_category_path(@workout_category), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show workout_category
%dl.dl-horizontal
  %dt Name:
  %dd= @workout_category.name
  %dt Description:
  %dd= @workout_category.description