config/routes.rb
Rails.application.routes.draw do

  resources :workout_categories
  resources :user_workouts do
    collection do
      get 'search_workout' => 'user_workouts#search_workout'
    end
  end 
  
  resources :workouts 
  # get 'dashboards/index'
  get "/dashboards", to: "dashboards#index"

  resources :meals
  resources :posts
  resources :categories
  devise_for :users	
  resources :todos

  root to: "dashboards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_workout.rb
# == Schema Information
#
# Table name: user_workouts
#
#  id         :integer          not null, primary key
#  set        :integer
#  rep        :integer
#  weight     :integer
#  workout_id :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserWorkout < ApplicationRecord
  belongs_to :workout
  belongs_to :user
end

app/controllers/user_workouts_controller.rb
class UserWorkoutsController < ApplicationController
  before_action :set_user_workout, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js

  # GET /user_workouts
  # GET /user_workouts.json
  def index
    @user_workouts = UserWorkout.all
  end

  # GET /user_workouts/1
  # GET /user_workouts/1.json
  def show
  end

  # GET /user_workouts/new
  def new
    @user_workout = UserWorkout.new
  end

  # GET /user_workouts/1/edit
  def edit
  end

  # POST /user_workouts
  # POST /user_workouts.json
  def create
    @user_workout = UserWorkout.new(user_workout_params)

    respond_to do |format|
      if @user_workout.save
        format.html { redirect_to @user_workout, notice: 'User workout was successfully created.' }
        format.json { render :show, status: :created, location: @user_workout }
      else
        format.html { render :new }
        format.json { render json: @user_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_workouts/1
  # PATCH/PUT /user_workouts/1.json
  def update
    respond_to do |format|
      if @user_workout.update(user_workout_params)
        format.html { redirect_to @user_workout, notice: 'User workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_workout }
      else
        format.html { render :edit }
        format.json { render json: @user_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_workouts/1
  # DELETE /user_workouts/1.json
  def destroy
    @user_workout.destroy
    respond_to do |format|
      format.html { redirect_to user_workouts_url, notice: 'User workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_workout
    @workout = _workout.where('name ILIKE ?', "%#{params[:term]}%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_workout
      @user_workout = UserWorkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_workout_params
      params.require(:user_workout).permit(:set, :rep, :weight, :workout_id, :user_id)
    end

    def _workout
      Workout
    end
end

app/helpers/user_workouts_helper.rb
module UserWorkoutsHelper
end

app/views/user_workouts/_form.html.haml
= form_for(@user_workout, html: { class: 'form-horizontal', role: 'form' }) do |f|
  - if @user_workout.errors.any?
    .alert.alert-danger.alert-dismissable{:role => 'alert'}
      %button.close{'data-dismiss' => 'alert', :type => 'button'}
        %span{'aria-hidden' => 'true'} ×
        %span.sr-only Close
      %h4
        = pluralize(@user_workout.errors.count, 'error')
        prohibited this user_workout from being saved:
      %ul
        - @user_workout.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-xs-4
      %span#load_image
    .col-xs-4
      %b SETS
      %h2 3
    .col-xs-4
      %b REPS
      %h2 12

  -#.form-group
  -#  = f.label :set, class: 'col-sm-2 control-label'
  -#  .col-sm-10
  -#    = f.number_field :set, class: 'form-control'
  -#.form-group
  -#  = f.label :rep, class: 'col-sm-2 control-label'
  -#  .col-sm-10
  -#    = f.number_field :rep, class: 'form-control'
  -#.form-group
  -#  = f.label :weight, class: 'col-sm-2 control-label'
  -#  .col-sm-10
  -#    = f.number_field :weight, class: 'form-control'
  -#.form-group
  -#  = f.label :workout, class: 'col-sm-2 control-label'
  -#  .col-sm-10
  -#    = f.text_field :workout, class: 'form-control'
  -#.form-group
  -#  = f.label :user, class: 'col-sm-2 control-label'
  -#  .col-sm-10
  -#    = f.text_field :user, class: 'form-control'
  -#.form-group
  -#  .col-sm-offset-2.col-sm-10
  -#    = f.submit class: 'btn btn-primary'

app/views/user_workouts/_searched_results.html.haml
%div#workout_grid
  - @workout.each do |w|
    .row.select_workout.display_design{id: "#{w.id}", image_url: "#{w.pictograms.first.url}", name: "#{w.name}"}
      .col-xs-12
        %span.workout_image
          = image_tag (w.pictograms.first.url rescue 'no image'), style: 'padding: 3px', size: '90x90'
        %span.workout_name
          %p= w.name

app/views/user_workouts/edit.html.haml
.page-header
  = link_to user_workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user_workout, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user_workout
= render 'form'

app/views/user_workouts/index.html.haml
.page-header
  = link_to new_user_workout_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User workout
  %h1 Listing user_workouts
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Set
        %th Rep
        %th Weight
        %th Workout
        %th User
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @user_workouts) do |user_workout|
        %td= user_workout.set
        %td= user_workout.rep
        %td= user_workout.weight
        %td= user_workout.workout
        %td= user_workout.user
        %td= link_to 'Show', user_workout
        %td= link_to 'Edit', edit_user_workout_path(user_workout)
        %td= link_to 'Destroy', user_workout, method: :delete, data: { confirm: 'Are you sure?' }

app/views/user_workouts/new.html.haml
.page-header
  = link_to user_workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h3 Add Training

%br
.row
  .col-lg-12
    = form_tag search_workout_user_workouts_path, method: :get, remote: true, class: 'input-group', id: 'search_id' do
      = text_field_tag :term, nil, class: 'form-control'
      %span.input-group-btn
        = submit_tag 'Search Exercise', class: 'btn btn-default'

%br

#show_results

%br

%div#workout_form
  = render 'form'

app/views/user_workouts/search_workout.js.erb
$("#show_results").hide().html("<%= escape_javascript(render('user_workouts/searched_results')) %>").fadeIn(500)

app/views/user_workouts/show.html.haml
.page-header
  = link_to user_workouts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_workout_path(@user_workout), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user_workout
%dl.dl-horizontal
  %dt Set:
  %dd= @user_workout.set
  %dt Rep:
  %dd= @user_workout.rep
  %dt Weight:
  %dd= @user_workout.weight
  %dt Workout:
  %dd= @user_workout.workout
  %dt User:
  %dd= @user_workout.user