config/routes.rb
Rails.application.routes.draw do

  resources :workout_categories
  resources :user_workouts do
    collection do
      get 'search_workout' => 'user_workouts#search_workout'
    end
  end 
  
  resources :workouts 
  # get 'dashboards/index'
  get "/dashboards", to: "dashboards#index"

  resources :meals
  resources :posts
  resources :categories
  devise_for :users	
  resources :todos

  root to: "dashboards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title keepMeFiit
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <haml_loud> javascript_include_tag &quot;https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js&quot;, &quot;https://oss.maxcdn.com/respond/1.4.2/respond.min.js&quot; </haml_loud>
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    /
      <style type="text/css">
      @font-face {
      font-family: 'a_sensible_armadilloregular';
      src: url('/assets/para/a_sensible_armadillo-webfont.eot');
      src: url('/assets/para/a_sensible_armadillo-webfont.eot?#iefix') format('embedded-opentype'),
      url('/assets/para/a_sensible_armadillo-webfont.woff') format('woff'),
      url('/assets/para/a_sensible_armadillo-webfont.ttf') format('truetype'),
      url('/assets/para/a_sensible_armadillo-webfont.svg#a_sensible_armadilloregular') format('svg');
      font-weight: normal;
      font-style: normal;
      }
      </style>
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation", :style => "background-color:#3498db; border-bottom-color:#3498db"}
      .container
        / <div class="navbar-header">
        /
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
        /= link_to "Keepmefiit", posts_path, class: "navbar-brand custom", style: "color: #ffffff"
        /%span{:style => "color:white;font-size:9px;text-decoration:italic;"} ALPHA '120x40'
        = image_tag('Logo_Orange.png', size: '110x38', style: 'padding-top:4px;padding-bottom:2px')
        / </div>
        / <div id="navbar" class="collapse navbar-collapse">
        /
          <ul class="nav navbar-nav navbar-right">
          <li> <haml_silent></haml_silent> </li>
          <haml_silent>
          </haml_silent>          <li><haml_silent></haml_silent> </li>
          <haml_silent>
          </haml_silent>          <li><haml_silent></haml_silent></li>
          <li><haml_silent></haml_silent></li>
          <haml_silent>
          </haml_silent>        </ul>
        %span{:onclick => "openNav()", :style => "float:right; color:#ffffff;font-size:30px;cursor:pointer"} ☰
        / </div>
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          = msg
      = yield
    #mySidenav.sidenav
      %a.closebtn{:href => "javascript:void(0)", :onclick => "closeNav()"} ×
      %span.custom.white Keepmefiit
      %span{:style => "color:white;font-size:9px;text-decoration:italic;"}
        %sup ALPHA

      %br/
      %br/
      = link_to 'POST', posts_path, class: "link-size", style: "color: #ffffff"
      = link_to 'DASHBOARD', dashboards_path, class: "link-size", style: "color: #ffffff"
      = link_to 'DB WORKOUTS', workouts_path, class: "link-size", style: "color: #ffffff"
      - if user_signed_in?
        = link_to 'ADD TRAINING', new_user_workout_path, class: 'link-size', style: 'color: #ffffff'
        = link_to "SIGN OUT", destroy_user_session_path, :method => :delete, class: "link-size", style: "color: #ffffff"
      - else
        = link_to "SIGN IN", new_user_session_path, class: "link-size", style: "color: #ffffff"
        = link_to "SIGN UP", new_user_registration_path, class: "link-size", style: "color: #ffffff"
    :javascript
      function openNav() {
          document.getElementById("mySidenav").style.width = "100%";
      }

      function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
      }